name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build scripts
        run: pnpm build

      - name: Build protocol package
        run: pnpm build:protocol

      - name: Run tests
        run: pnpm test

      - name: Enforce protocol changeset
        run: pnpm protocol:changeset-check
